### ISSUE TITLE
Card Payment Service - Monitor - Exception

### ISSUE THREAD

**Issue by Pandolfou** [paysafegroup/paysafe_sdk_csharp#13]
I have a customer that use the sdk from about two years ago and today we got an exception « Object not set to a reference of an object. » on client.cardPaymentService().monitor(). Same issue on Authorize(). The CardPaymentService object is not null.

Thanks for help!

**Comment by Pandolfou** [comment]
Hello someone can help??

**Comment by francoisneron** [comment]
@Pandolfou Could you provide the logs? It should have been fixed on our latest pull request (5 days ago).

**Comment by Pandolfou** [comment]
@francoisneron I don't have the logs, but I have downloaded the project and modify the sampleApp to call client.cardPaymentService().monitor(); As you can see in the attachment, I have an exception related to the SSL/TLS secure channel and then the null reference occurs in the catch part. So, there is two issue.
![paysafe_exception](https://user-images.githubusercontent.com/8547177/42775476-6791f4f6-8902-11e8-9620-c691786846e4.jpg)

**Comment by francoisneron** [comment]
If you are using .NET, you need to make sure that the version you are using supports TLS1.2. 
https://stackoverflow.com/questions/37869135/is-that-possible-to-send-httpwebrequest-using-tls1-2-on-net-4-0-framework

**Comment by Pandolfou** [comment]
The fix is working. Thank you!
